#!/usr/bin/env/bash
#
#   ~/.bash/aliases (macOS)
#
#     Custom user defined aliases.
#     Sourced by ~/.bashrc.
#
#   Neel Yadav
#   06.29.2021


# Quick SSH locations specified on a per-user basis (don't want public here)
[ -r ~/.ssh/host_aliases ] && . $HOME/.ssh/host_aliases

# Shorthand aliases
alias up='cd ..'
alias cd..='cd ..'
alias tth='terminal-to-html'

# Aliases 2 small 2 function
alias reload-shell='clear;[[ -r ~/.bash_profile ]] && . ~/.bash_profile || echo "err"'
alias fresh-brew='sudo -v && brew update && brew upgrade && brew upgrade --cask && brew autoremove && brew cleanup --prune 0'
alias path-list='echo $PATH | sed -E "s/:/\n/g"'

# El-iases
alias lss='ls -Alth'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Git aliases
alias adog='git log --all --decorate --oneline --graph'
alias dot='git --git-dir=$HOME/Git/dotfiles.git/ --work-tree=$HOME'
alias recent='git recent'
alias commit='f() { git commit -m "$*" 1> /dev/null && recent; unset f; }; f'
alias uncommit='git reset --soft HEAD~1'    # undo last commit; keep changes
alias delcommit='git reset --hard HEAD~1'   # undo last commit; discard changes

# Clipboard content shortcut
alias copy='f() { [[ -r "$1" ]] && pbcopy < "$1" || pbcopy <<< "$*"; unset f; }; f'
alias paste='echo "$(pbpaste)"'

# Defined in .bashrc but commented out here for reference
#alias wget='wget --hsts-file ~/.history/wget-hsts'
#alias alpine='alpine -p "$HOME/.config/alpine/pinerc" -pwdcertdir "$HOME/.config/alpine/smime"'

